version: '3.9'

services:
  redis:
    container_name: redis
    image: redis
    restart : always
    ports:
    -  "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  chatapp:
    build: .
    container_name: chatapp
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
       - DJANGO_SECRET_KEY=test
       - DJANGO_DEBUG=True
    depends_on:
      - redis
    links:
      - redis