version: '3.9'

services:
  chatapp:
    build: .
    container_name: chatapp
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
       - DJANGO_SECRET_KEY=test
       - DJANGO_DEBUG=True