# Generated by Django 5.0.6 on 2024-05-30 21:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0][9][0-9][0-9]{8,8}$')])),
                ('bio', models.CharField(max_length=300)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
