# Generated by Django 5.0.6 on 2024-06-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='created_date',
            new_name='follow_data',
        ),
    ]
