# Generated by Django 5.0.6 on 2024-06-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
