# Generated by Django 5.0.6 on 2024-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_rename_like_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="picture",
            field=models.ImageField(null=True, upload_to="social/post_pictures"),
        ),
    ]
