# Generated by Django 5.0.6 on 2024-06-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_comment_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
